#!/usr/bin/env bash
# Script to change localhost addresses

# Copy /etc/hosts to ~/hosts.new
cp /etc/hosts ~/hosts.new

# Modify ~/hosts.new
echo "127.0.0.2       localhost" > ~/hosts.new
echo "8.8.8.8         facebook.com" >> ~/hosts.new

# Replace /etc/hosts with the modified file
sudo cp -f ~/hosts.new /etc/hosts

# Clean up temporary file
rm ~/hosts.new

echo "Hosts file modified successfully!"
