#!/usr/bin/env bash
# This Script connects to the server 54.82.196.192 using the users private key
# stored in a file school Found in the users home directory

eval $("ssh-agent")

ssh-add ~/.ssh/school

ssh ubuntu@54.82.196.192
